version: "3.8"
name: iread-app

services:
  backend:
    image: guillermopalacios/iread-backend-app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://bd:3306/iread_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=129837465lg
      - URL_FRONT=http://localhost:4200
    ports:
      - "8089:8080"
    networks:
      - iread-net
    depends_on:
      - bd

  bd:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=129837465lg
      - MYSQL_DATABASE=iread_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - iread-net

volumes:
  mysql_data:

networks:
  iread-net:
    driver: bridge