name: Docker Image Back-End CI

on:
  push:
    branches:
      - deploy
    paths:
      - 'iRead-Project-Narrative-backend/**'
      - '.github/workflows/docker-back.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Backend iRead image
        uses: docker/build-push-action@v3
        with:
          context: ./iRead-Project-Narrative-backend
          file: ./iRead-Project-Narrative-backend/Dockerfile
          push: true
          tags: guillermopalacios/iread-backend-app
